server:
  port: 9998

spring:
  jpa:
    database: POSTGRESQL
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/comp
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
